server:
  servlet:
    context-path: /BE

app:
  base-url: ${BASE_URL}
  frontend-url: ${FRONTEND_URL}
  jwt:
    secret: ${JWT_SECRET}
    expiration: 3600000 # 60min in milliseconds

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

google:
  client-id: ${GOOGLE_CLIENT_ID}

spring:
  application:
    name: EduPrompt

  datasource:
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SENDER_EMAIL}
    password: ${SENDER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

  sendgrid:
    api-key: ${SENDGRID_API_KEY}
    from:
      email: ${SENDGRID_FROM_EMAIL}

  data:
    redis:
      host: ${REDISHOST}
      port: ${REDISPORT}
      password: ${REDISPASSWORD:}
      timeout: 30000
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2
          max-wait: 3000ms
        shutdown-timeout: 500ms

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

open:
  api:
    title: "EduPrompt"
    version: "1.0"
    description: "API document of project EduPrompt"
    server:
      url: "${BASE_URL}${server.servlet.context-path}"
      description: "SpringBoot"
    group: "SEP490"
    scan-package: "SEP490.EduPrompt.controller"

openai:
  api-key: ${OPENAI_API_KEY}
  timeout: 30s
gemini:
  api-key: ${GEMINI_API_KEY}
  file-search-store: "fileSearchStores/somethin-ewzxgazaxwbo"

## Postmark Configuration
#postmark:
#  api-token: ${POSTMARK_API_KEY}
#  from-email: ${POSTMARK_EMAIL}
#  template:
#    verification: ${POSTMARK_VERIFICATION_TEMPLATE_ID}
#    password-reset: ${POSTMARK_PASSWORD_RESET_TEMPLATE_ID}
#    welcome: ${POSTMARK_WELCOME_TEMPLATE_ID}

