server:
  servlet:
    context-path: /BE

spring:
  application:
    name: EduPrompt

  datasource:
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

open:
  api:
    title: "EduPrompt"
    version: "1.0"
    description: "API document of project EduPrompt"
    server:
      url: "${BASE_URL}${server.servlet.context-path}"
      description: "SpringBoot"
    group: "SEP490"
    scan-package: "SEP490.EduPrompt.controller"

# JWT Configuration
jwt:
  secret: "mySecretKey123456789012345678901234567890"
  expiration: 86400000 # 24 hours in milliseconds


