server:
  servlet:
    context-path: /BE

app:
  base-url: ${BASE_URL}
  frontend-url: ${FRONTEND_URL}
  jwt:
    secret: ${JWT_SECRET}
    expiration: 60000 * 15 # 15min in milliseconds

spring:
  application:
    name: EduPrompt

  datasource:
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SENDER_EMAIL}
    password: ${SENDER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

open:
  api:
    title: "EduPrompt"
    version: "1.0"
    description: "API document of project EduPrompt"
    server:
      url: "${BASE_URL}${server.servlet.context-path}"
      description: "SpringBoot"
    group: "SEP490"
    scan-package: "SEP490.EduPrompt.controller"




